version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=10485760
      - ALLOWED_EXTENSIONS=pdf,docx,txt
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - DEBUG=True
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - hireagent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - hireagent-network

networks:
  hireagent-network:
    driver: bridge

volumes:
  uploads:
    driver: local 